
state = {
  newGame: false,
  turn: null,
  players: [
    {
      player1: null,
      foreverChips: 2,
      destroyDiagonalChips: 1,
      destroyHorizontalChips: 1,
    },
    {
      player2: null,
      foreverChips: 2,
      destroyDiagonalChips: 1,
      destroyHorizontalChips: 1,
    },
  ],
  gameBoard: [
    [
      { x: 1, y: 1, contents: "empty" },
      { x: 2, y: 1, contents: "empty" },
      { x: 3, y: 1, contents: "empty" },
      { x: 4, y: 1, contents: "empty" },
      { x: 5, y: 1, contents: "empty" },
      { x: 6, y: 1, contents: "empty" },
      { x: 7, y: 1, contents: "empty" },
    ],
    [
      { x: 1, y: 2, contents: "empty" },
      { x: 2, y: 2, contents: "empty" },
      { x: 3, y: 2, contents: "empty" },
      { x: 4, y: 2, contents: "empty" },
      { x: 5, y: 2, contents: "empty" },
      { x: 6, y: 2, contents: "empty" },
      { x: 7, y: 2, contents: "empty" },
    ],
    [
      { x: 1, y: 3, contents: "empty" },
      { x: 2, y: 3, contents: "empty" },
      { x: 3, y: 3, contents: "empty" },
      { x: 4, y: 3, contents: "empty" },
      { x: 5, y: 3, contents: "empty" },
      { x: 6, y: 3, contents: "empty" },
      { x: 7, y: 3, contents: "empty" },
    ],
    [
      { x: 1, y: 4, contents: "empty" },
      { x: 2, y: 4, contents: "empty" },
      { x: 3, y: 4, contents: "empty" },
      { x: 4, y: 4, contents: "empty" },
      { x: 5, y: 4, contents: "empty" },
      { x: 6, y: 4, contents: "empty" },
      { x: 7, y: 4, contents: "empty" },
    ],
    [
      { x: 1, y: 5, contents: "empty" },
      { x: 2, y: 5, contents: "empty" },
      { x: 3, y: 5, contents: "empty" },
      { x: 4, y: 5, contents: "empty" },
      { x: 5, y: 5, contents: "empty" },
      { x: 6, y: 5, contents: "empty" },
      { x: 7, y: 5, contents: "empty" },
    ],
    [
      { x: 1, y: 6, contents: "empty" },
      { x: 2, y: 6, contents: "empty" },
      { x: 3, y: 6, contents: "empty" },
      { x: 4, y: 6, contents: "empty" },
      { x: 5, y: 6, contents: "empty" },
      { x: 6, y: 6, contents: "empty" },
      { x: 7, y: 6, contents: "empty" },
    ],
  ],
};